### ISSUE TITLE
net.praseodym.activelearner.ActivelearnerApplication required a bean of type 'de.learnlib.api.LearningAlgorithm$MealyLearner'

### ISSUE THREAD

**Issue by Kortekaasy** [praseodym/learning-fuzzing#1]
I tried to run the active learner using  the command `java -Djava.library.path=~/learning-fuzzing/afl/build/ -jar activelearner-0.1.0-SNAPSHOT.jar --spring.profiles.active=target-rers1`, but when executed I get the error message:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method experiment in net.praseodym.activelearner.ActivelearnerApplication required a bean of type 'de.learnlib.api.LearningAlgorithm$MealyLearner' that could not be found.


Action:

Consider defining a bean of type 'de.learnlib.api.LearningAlgorithm$MealyLearner' in your configuration.
```

I have the feeling that somehow the application cannot find the LearnLib library. I did install the forked version of learnlib mentioned in the readme, using `mvn install`. Can anyone verify whether this is my problem, and explain to me how to solve this issue?

**Comment by praseodym** [comment]
I think the problem is not that the application cannot find the LearnLib library, but that you’re missing a Spring profile that configures which learning algorithm should be used. 

For example, to use the L* algorithm, add the `lstar` profile (e.g. `--spring.profiles.active=target-rers1,lstar`):

https://github.com/praseodym/learning-fuzzing/blob/db3ee88dcb7ab9306289efba5ad1b28037d0b14a/activelearner/src/main/java/net/praseodym/activelearner/ActivelearnerApplication.java#L114-L120

Other missing beans can be resolved in a similar fashion by looking at the definitions in [`ActivelearnerApplication.java`](https://github.com/praseodym/learning-fuzzing/blob/master/activelearner/src/main/java/net/praseodym/activelearner/ActivelearnerApplication.java).

(The README can definitely use some work!)
